services:
  postgres:
    image: postgres:16
    container_name: helpdesk_postgres
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - helpdesk_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: helpdesk_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - helpdesk_network

  app:
    build: .
    container_name: helpdesk_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/helpdesk_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - helpdesk_network

volumes:
  postgres_data:

networks:
  helpdesk_network: